In [19]:
cd /Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts/

/Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts

/Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts/.venv/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [20]:
import logging
import pandas as pd

from general_functions.return_workspace_ids import return_workspace_ids
from general_functions.constants import return_api_url
from general_functions.call_api_with_account_id import call_api_with_accountId, send_to_innkeepr_api_paginated

In [21]:
customer = "MissPompadour GmbH"
source = "facebook"
url = return_api_url()
url = "https://api.innkeepr.ai/api"
print(f"url = {url}")
account_ids = return_workspace_ids()
account_id = [acc["id"] for acc in account_ids if acc["name"] == customer]
if len(account_id) != 1:
    print(sorted([account["name"] for account in account_ids]))
account_id = account_id[0]

url = https://api.innkeepr.ai/api
https://targeting.innkeepr.ai/api/core/workspaces/query

In [22]:
sources = call_api_with_accountId(
    f"{url}/sources/query",
    account_id,
    {"name":source},
    logging
)
print(sources)
if len(sources) != 1:
    raise Exception(f"more or less than one source was found: {sources}")
source_id = sources[0]["id"]
print(f"source_id = {source_id}")

[{'id': '5ee5dc05aeb18c0427aa3e06', 'name': 'facebook', 'displayName': 'Facebook', 'options': {'eventRoutingEnabled': True, 'targetingAvailable': True, 'urlTrackingAvailable': True, 'urlTrackingParam': 'klar_adid', 'urlCampaignParam': None}, 'config': {'adAccounts': [{'id': '419376528907590', 'name': 'MissPompadour Ads', 'businessName': 'MissPompadour GmbH', 'currency': 'EUR'}], 'pixelIds': ['2386658378283067'], 'user': {'email': '', 'name': 'Henriette Bode', 'timestamp': '2026-06-09T10:13:50.685Z'}}, 'url': 'https://facebook.com', 'status': 'active', 'statusText': '', 'category': 'advertising', 'createdAt': '2026-06-09T10:13:49.687Z'}]
source_id = 5ee5dc05aeb18c0427aa3e06

In [23]:
treatments = send_to_innkeepr_api_paginated(
    f"{url}/treatments/query",
    account_id,
    {"source":source_id},
    logging
)
treatments = pd.json_normalize(treatments)

In [24]:
treatments.to_csv("treatments.csv")

In [25]:
treatments["source"].value_counts()

5ee5dc05aeb18c0427aa3e06    63
Name: source, dtype: int64

In [26]:
for col in treatments.columns:
    temp = treatments[treatments[col].str.contains("23790390868").fillna(False)]
    if len(temp) > 0:
        print(col)
        print(temp[col])

In [27]:
treatments["properties.type"].value_counts()

DISPLAY    63
Name: properties.type, dtype: int64

In [ ]:
# temp = treatments[treatments["properties.status"]=="active"].groupby(by=["relates_to.campaign.name","relates_to.adset.name","properties.adAccountName"])['id'].value_counts().reset_index()
# temp_ad_set_name = temp["relates_to.adset.name"].unique().tolist()
# temp

In [29]:
if 'relates_to.adset.name' in treatments.columns:
    vc = treatments.groupby(by=["relates_to.campaign.name","relates_to.adset.name","properties.adAccountName"])['id'].value_counts()
elif "relates_to.assetGroup.name" in treatments.columns:
    vc = treatments.groupby(by=["relates_to.campaign.name","relates_to.assetGroup.name","properties.adAccountName"])['id'].value_counts()
else:
    vc = treatments.groupby(by=["relates_to.campaign.name","properties.adAccountName"])['id'].value_counts()
vc = vc.rename("count").reset_index()
vc

,relates_to.campaign.name,relates_to.adset.name,properties.adAccountName,id,count
0,AT_NC_ASC_Käufe_BalkonGartenLack_022026,AT_ASC_Broad_BalkonGartenLack,MissPompadour Ads,69deca5887320b6c0f1461a2,1
1,AT_NC_ASC_Käufe_BalkonGarten_StreichSet_032026,AT_ASC_Broad_BalkonGarten_StreichSet,MissPompadour Ads,69deca5887320b6c0f14619e,1
2,AT_NC_ASC_Käufe_BestPerformer_122025,AT_ASC_Broad_BestPerformer,MissPompadour Ads,69deca5887320b6c0f1461ac,1
3,AT_NC_ASC_Käufe_Farbenfreitag_052026,AT_ASC_Broad_Farbenfreitag,MissPompadour Ads,6a177ae287320b63b519a814,1
4,AT_NC_ASC_Käufe_GratisTapetenkleister_042026,AT_ASC_Broad_GratisTapetenkleister,MissPompadour Ads,69e16d5687320bcd425fb372,1
...,...,...,...,...,...
58,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...,DE_Manuell_Innkeepr_Seeds_Broad,MissPompadour Ads,6a23583987320b605f0adb04,1
59,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...,DE_Manuell_Innkeepr_Seeds_LAL_10Prozent,MissPompadour Ads,6a23583987320b605f0adb05,1
60,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...,DE_Manuell_Innkeepr_Seeds_LAL_1Prozent,MissPompadour Ads,6a23583987320b605f0adb07,1
61,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...,DE_Manuell_Innkeepr_Seeds_LAL_5-10Prozent,MissPompadour Ads,6a23583987320b605f0adb06,1
62,DE_Traffic_DonkeySchatzsuche_Teasing_052026,DE_Manual_DonkeySchatzsuche_Teasing,MissPompadour Ads,69f3e25d87320b87640e8206,1

In [30]:
vc.drop_duplicates(subset=["relates_to.campaign.name"])

,relates_to.campaign.name,relates_to.adset.name,properties.adAccountName,id,count
0,AT_NC_ASC_Käufe_BalkonGartenLack_022026,AT_ASC_Broad_BalkonGartenLack,MissPompadour Ads,69deca5887320b6c0f1461a2,1
1,AT_NC_ASC_Käufe_BalkonGarten_StreichSet_032026,AT_ASC_Broad_BalkonGarten_StreichSet,MissPompadour Ads,69deca5887320b6c0f14619e,1
2,AT_NC_ASC_Käufe_BestPerformer_122025,AT_ASC_Broad_BestPerformer,MissPompadour Ads,69deca5887320b6c0f1461ac,1
3,AT_NC_ASC_Käufe_Farbenfreitag_052026,AT_ASC_Broad_Farbenfreitag,MissPompadour Ads,6a177ae287320b63b519a814,1
4,AT_NC_ASC_Käufe_GratisTapetenkleister_042026,AT_ASC_Broad_GratisTapetenkleister,MissPompadour Ads,69e16d5687320bcd425fb372,1
5,AT_NC_ASC_Käufe_Himmelfahrt_052026,AT_ASC_Broad_Himmelfahrt,MissPompadour Ads,69f290c587320be2fc14bbe6,1
6,AT_NC_ASC_Käufe_Ikea_122025,AT_ASC_Broad_Ikea,MissPompadour Ads,69deca5887320b6c0f1461ad,1
7,AT_NC_ASC_Käufe_Nikolaus_Überraschung_122025,AT_ASC_Broad_Nikolaus,MissPompadour Ads,69deca5887320b6c0f1461af,1
8,AT_NC_ASC_Käufe_OutdoorWochenende_062026,AT_ASC_Broad_OutdoorWochenende,MissPompadour Ads,6a274cdd87320bb07070a0ef,1
9,AT_NC_ASC_Käufe_StreichInDenMai_VKfrei_052026,AT_ASC_Broad_StreichInDenMai_VKFrei,MissPompadour Ads,69f13f4b87320bfb82039c82,1
10,AT_NC_ASC_Reichweite_022026,AT_ASC_Broad_Reichweite,MissPompadour Ads,69deca5887320b6c0f1461a5,1
11,CH_NC_ASC+_Conversion_Bestperformer Ads_082024,CH_ASC+_all exclu. BK_Bestperformer Ads,MissPompadour Ads,69deca5887320b6c0f1461b7,1
12,CH_NC_ASC_Käufe_BalkonGartenLack_022026,CH_ASC_Broad_BalkonGartenLack,MissPompadour Ads,69deca5887320b6c0f1461a1,1
13,CH_NC_ASC_Käufe_Farbenfreitag_052026,CH_ASC_Broad_Farbenfreitag,MissPompadour Ads,6a177ae287320b63b519a813,1
14,CH_NC_ASC_Käufe_Himmelfahrt_052026,CH_ASC_Broad_Himmelfahrt,MissPompadour Ads,69f290c587320be2fc14bbe5,1
15,CH_NC_ASC_Käufe_Ikea_122025,CH_ASC_Broad_Ikea_KW49,MissPompadour Ads,69deca5887320b6c0f1461ae,1
16,CH_NC_ASC_Käufe_OutdoorWochenende_062026,CH_ASC_Broad_OutdoorWochenende,MissPompadour Ads,6a274cdd87320bb07070a0ee,1
17,CH_NC_ASC_Käufe_StreichInDenMai_VKfrei_052026,CH_ASC_Broad_StreichInDenMai_VKFrei,MissPompadour Ads,69f13f4b87320bfb82039c81,1
18,CH_NC_ASC_Reichweite_022026,CH_ASC_Broad_Reichweite,MissPompadour Ads,69deca5887320b6c0f1461a4,1
19,DE_NC_ASC_Käufe_Bad_Fliesen_062026,DE_ASC_Broad_Bad_Fliesen,MissPompadour Ads,6a23583987320b605f0adb09,1
21,DE_NC_ASC_Käufe_BalkonGartenLack_022026,DE_ASC_Broad_BalkonGartenLack,MissPompadour Ads,69deca5887320b6c0f1461a3,1
22,DE_NC_ASC_Käufe_BalkonGarten_StreichSet_032026,DE_ASC_Broad_BalkonGarten_StreichSet,MissPompadour Ads,69deca5887320b6c0f14619f,1
23,DE_NC_ASC_Käufe_BestPerformer_102025,DE_ASC_Broad_BestPerformer,MissPompadour Ads,69deca5887320b6c0f1461b6,1
24,DE_NC_ASC_Käufe_Carousels_042026,DE_ASC_Broad_Carousels,MissPompadour Ads,69f3e25d87320b87640e8207,1
25,DE_NC_ASC_Käufe_CosyColours_102025,DE_ASC_Broad_CosyColours,MissPompadour Ads,69deca5887320b6c0f1461b5,1
26,DE_NC_ASC_Käufe_CosyColours_Wandfarben_112025,DE_ASC_Broad_CosyColours_Wandfarben,MissPompadour Ads,69deca5887320b6c0f1461b2,1
27,DE_NC_ASC_Käufe_DieNützliche_012026,DE_ASC_Broad_DieNützliche,MissPompadour Ads,69deca5887320b6c0f1461a7,1
28,DE_NC_ASC_Käufe_Farbenfreitag_052026,DE_ASC_Broad_Farbenfreitag,MissPompadour Ads,6a177ae287320b63b519a815,1
29,DE_NC_ASC_Käufe_Farbkarten_112025,DE_ASC_Broad_Farbkarten_Zubehör,MissPompadour Ads,69deca5887320b6c0f1461b1,1
30,DE_NC_ASC_Käufe_Garten_ASL_022026,DE_ASC_Broad_Garten_ASL,MissPompadour Ads,69deca5887320b6c0f1461a0,1
31,DE_NC_ASC_Käufe_GratisTapetenkleister_042026,DE_ASC_Broad_GratisTapetenkleister,MissPompadour Ads,69e16d5687320bcd425fb373,1
32,DE_NC_ASC_Käufe_Grundierung_0526,DE_ASC_Broad_Grundierung,MissPompadour Ads,6a16295e87320bb4a2658715,1
33,DE_NC_ASC_Käufe_Himmelfahrt_052026,DE_ASC_Broad_Himmelfahrt,MissPompadour Ads,69f290c587320be2fc14bbe7,1
34,DE_NC_ASC_Käufe_Ikea_102025,DE_ASC_Broad_Ikea,MissPompadour Ads,69deca5887320b6c0f1461b4,1
35,DE_NC_ASC_Käufe_Kostenvergleich_042026,DE_ASC_Broad_Kostenvergleich,MissPompadour Ads,69f290c587320be2fc14bbe8,1
36,DE_NC_ASC_Käufe_LP_Test_Ikea_052026,DE_ASC_Broad_Ikea,MissPompadour Ads,6a0ceed987320b8cce645a57,1
37,DE_NC_ASC_Käufe_LittlePomp_012026,DE_ASC_LittlePomp_Vorschlag_LAL_VisitorLP,MissPompadour Ads,69deca5887320b6c0f1461a9,1
38,DE_NC_ASC_Käufe_Möbel_122025,DE_ASC_Broad_Möbel,MissPompadour Ads,69deca5887320b6c0f1461ab,1
39,DE_NC_ASC_Käufe_Nikolaus_Überraschung_122025,DE_ASC_Broad_Nikolaus,MissPompadour Ads,69deca5887320b6c0f1461b0,1
40,DE_NC_ASC_Käufe_OutdoorWochenende_062026,DE_ASC_Broad_OutdoorWochenende,MissPompadour Ads,6a274cdd87320bb07070a0f1,1
41,DE_NC_ASC_Käufe_OutdoorWochenende_Retargeting_...,DE_ASC_Broad_OutdoorWochenende_Websitevisitor180d,MissPompadour Ads,6a274cdd87320bb07070a0f0,1
42,DE_NC_ASC_Käufe_StreichInDenMai_VKfrei_052026,DE_ASC_Broad_StreichInDenMai_VKFrei,MissPompadour Ads,69f13f4b87320bfb82039c83,1
43,DE_NC_ASC_Käufe_Tapeten_012026,DE_ASC_Broad_Tapeten,MissPompadour Ads,69deca5887320b6c0f1461a8,1
44,DE_NC_ASC_Käufe_Tapeten_VillaKarole_042026,DE_ASC_Broad_Tapeten_VillaKarole,MissPompadour Ads,69deca5887320b6c0f146194,1
45,DE_NC_ASC_Käufe_Türen_102025,DE_ASC_Broad_Türen,MissPompadour Ads,69deca5887320b6c0f1461b3,1
46,DE_NC_ASC_Käufe_Urlaubsfeeling_052026,DE_ASC_Broad_Urlaubsfeeling,MissPompadour Ads,6a0f91d487320b2c0834279b,1
47,DE_NC_ASC_Käufe_Wände_122026,DE_ASC_Broad_Wände,MissPompadour Ads,69deca5887320b6c0f1461aa,1
48,DE_NC_ASC_Reichweite_022026,DE_ASC_Broad_Reichweite,MissPompadour Ads,69deca5887320b6c0f1461a6,1
49,DE_NC_Manual_Testing Kampagne_112024,DE_Manual_Broad_ASL_USPs_Static_AlleProjekte,MissPompadour Ads,69deca5887320b6c0f14619a,1
58,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...,DE_Manuell_Innkeepr_Seeds_Broad,MissPompadour Ads,6a23583987320b605f0adb04,1
62,DE_Traffic_DonkeySchatzsuche_Teasing_052026,DE_Manual_DonkeySchatzsuche_Teasing,MissPompadour Ads,69f3e25d87320b87640e8206,1

In [35]:
vc_filtered = treatments[
        # treatments["relates_to.campaign.name"].str.contains("🟠 DE // TOFU // ABO Sales // Creative Testing // ALL Formats // 06.08.2025", case=False).fillna(False) |
        # treatments["relates_to.campaign.name"].str.contains("🟠 DE // TOFU // ABO Sales // Inkeepr Creative Testing // ALL Formats // 15.10.2025", case=False).fillna(False) |
        # treatments["relates_to.campaign.name"].str.contains("🟠🟢 DEAT // TOFU // ABO Sales // Creative Testing // ALL Formats // 21.10.2025", case=False).fillna(False) 
        #treatments["relates_to.campaign.name"].str.contains("🟠🟢 DEAT // TOFU // ABO Sales // Innkeepr Testing // Iced Coffee // Statics // 01.12.2025", case=False).fillna(False)
        # treatments["relates_to.campaign.name"].str.contains("080126", case=False).fillna(False) |
        # treatments["relates_to.adset.name"].str.contains("080126", case=False).fillna(False) |
        #DE | Shopping | PMax | Rest | tROAS | 1100% 17.02 | 1200% 12.02 | 1200 990 1100 1250
        treatments["relates_to.campaign.name"].str.contains("Performer", case=False).fillna(False) 

        #treatments["relates_to.campaign.name"].str.contains("bottom5p_css", case=False).fillna(False)
    ]
vc_filtered.drop_duplicates(subset=["relates_to.campaign.name"])

,id,externalId,connection,source,name,lastUpdated,created,properties.type,properties.status,properties.adAccountId,properties.adAccountName,relates_to.adset.id,relates_to.adset.name,relates_to.campaign.id,relates_to.campaign.name
30,6a23583987320b605f0adb04,120247851912460431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_Manuell_Innkeepr_Seeds_Broad,2026-06-08T23:14:37.311Z,2026-06-05T06:32:54.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120247851912460431,DE_Manuell_Innkeepr_Seeds_Broad,120247849303660431,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...
56,69deca5887320b6c0f1461ac,120237653818290431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,AT_ASC_Broad_BestPerformer,2026-06-08T23:14:37.311Z,2025-12-03T12:58:08.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120237653818290431,AT_ASC_Broad_BestPerformer,120237653817070431,AT_NC_ASC_Käufe_BestPerformer_122025
61,69deca5887320b6c0f1461b6,120233867167650431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_ASC_Broad_BestPerformer,2026-06-08T23:14:37.311Z,2025-10-06T13:23:03.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120233867167650431,DE_ASC_Broad_BestPerformer,120233867166820431,DE_NC_ASC_Käufe_BestPerformer_102025
62,69deca5887320b6c0f1461b7,120211295514950431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,CH_ASC+_all exclu. BK_Bestperformer Ads,2026-06-08T23:14:37.311Z,2024-08-27T13:43:43.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120211295514950431,CH_ASC+_all exclu. BK_Bestperformer Ads,120211295514940431,CH_NC_ASC+_Conversion_Bestperformer Ads_082024

In [36]:
vc_filtered["relates_to.campaign.name"].drop_duplicates().sort_values()

56                 AT_NC_ASC_Käufe_BestPerformer_122025
62       CH_NC_ASC+_Conversion_Bestperformer Ads_082024
61                 DE_NC_ASC_Käufe_BestPerformer_102025
30    DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...
Name: relates_to.campaign.name, dtype: object

In [37]:
treatments_filtered=treatments[treatments["id"].isin(vc_filtered["id"].unique().tolist())]
treatments_filtered#["properties.status"].value_counts()

,id,externalId,connection,source,name,lastUpdated,created,properties.type,properties.status,properties.adAccountId,properties.adAccountName,relates_to.adset.id,relates_to.adset.name,relates_to.campaign.id,relates_to.campaign.name
30,6a23583987320b605f0adb04,120247851912460431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_Manuell_Innkeepr_Seeds_Broad,2026-06-08T23:14:37.311Z,2026-06-05T06:32:54.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120247851912460431,DE_Manuell_Innkeepr_Seeds_Broad,120247849303660431,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...
31,6a23583987320b605f0adb05,120247849863330431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_Manuell_Innkeepr_Seeds_LAL_10Prozent,2026-06-08T23:14:37.311Z,2026-06-05T05:58:49.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120247849863330431,DE_Manuell_Innkeepr_Seeds_LAL_10Prozent,120247849303660431,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...
32,6a23583987320b605f0adb06,120247849710210431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_Manuell_Innkeepr_Seeds_LAL_5-10Prozent,2026-06-08T23:14:37.311Z,2026-06-05T05:58:36.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120247849710210431,DE_Manuell_Innkeepr_Seeds_LAL_5-10Prozent,120247849303660431,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...
33,6a23583987320b605f0adb07,120247849303670431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_Manuell_Innkeepr_Seeds_LAL_1Prozent,2026-06-08T23:14:37.311Z,2026-06-05T05:58:36.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120247849303670431,DE_Manuell_Innkeepr_Seeds_LAL_1Prozent,120247849303660431,DE_NC_Manuell_Käufe_BestPerformer_Innkeepr_See...
56,69deca5887320b6c0f1461ac,120237653818290431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,AT_ASC_Broad_BestPerformer,2026-06-08T23:14:37.311Z,2025-12-03T12:58:08.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120237653818290431,AT_ASC_Broad_BestPerformer,120237653817070431,AT_NC_ASC_Käufe_BestPerformer_122025
61,69deca5887320b6c0f1461b6,120233867167650431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,DE_ASC_Broad_BestPerformer,2026-06-08T23:14:37.311Z,2025-10-06T13:23:03.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120233867167650431,DE_ASC_Broad_BestPerformer,120233867166820431,DE_NC_ASC_Käufe_BestPerformer_102025
62,69deca5887320b6c0f1461b7,120211295514950431,5ee5dc05aeb18c0427aa3e06,5ee5dc05aeb18c0427aa3e06,CH_ASC+_all exclu. BK_Bestperformer Ads,2026-06-08T23:14:37.311Z,2024-08-27T13:43:43.000Z,DISPLAY,active,419376528907590,MissPompadour Ads,120211295514950431,CH_ASC+_all exclu. BK_Bestperformer Ads,120211295514940431,CH_NC_ASC+_Conversion_Bestperformer Ads_082024

In [38]:
treatments_list = vc_filtered["id"].unique().tolist()
len(treatments_list), treatments_list

(7,
 ['6a23583987320b605f0adb04',
  '6a23583987320b605f0adb05',
  '6a23583987320b605f0adb06',
  '6a23583987320b605f0adb07',
  '69deca5887320b6c0f1461ac',
  '69deca5887320b6c0f1461b6',
  '69deca5887320b6c0f1461b7'])

In [ ]:
"6973681ac270576b5a39f95b",
  "6973681ac270576b5a39f95e",
  "6973681ac270576b5a39f965",
  "6973681ac270576b5a39f966",
  "6973681ac270576b5a39f985",
  "6973681ac270576b5a39f986",
  "6973681ac270576b5a39f987",
  "6973681ac270576b5a39f988",
  "6973681ac270576b5a39f9c3",
  "6973681ac270576b5a39f95c",
  "6973681ac270576b5a39f95d"

In [ ]:
len(treatments["id"].unique().tolist())

In [ ]:
treatments["created"].min(), treatments["created"].max()

In [ ]:
treatments["id"].unique().tolist()

In [ ]:
# externalIds = treatments_filtered["relates_to.assetGroup.id"].dropna().unique().tolist() #4 ['6599333130', '6627040705', '6624995271', '6624995298']
# externalIds = treatments_filtered["externalId"].dropna().unique().tolist() #4 ['6599333130', '6627040705', '6624995271', '6624995298']
# campaign_name = treatments_filtered["relates_to.campaign.name"].dropna().unique().tolist()
# print(campaign_name)
# print(len(externalIds), externalIds)
# test = send_to_innkeepr_api_paginated(
#     f"{url}/signals/query",
#     account_id,
#     {"relates_to.campaign.name":campaign_name},#externalId
#     logging
# )
# test

# Treatments via List

In [ ]:
treatment_file = pd.read_csv("/Users/karolinegriesbach/Downloads/SEA Suchkampagnen DACH.csv",sep=";")
treatment_file

In [ ]:
#treatment_file = treatment_file[treatment_file["Kampagnenname"].str.contains("BRAND", case=False)]
treatment_file

In [ ]:
treatments["relates_to.campaign.name"]

In [ ]:
used_treatments = pd.DataFrame()
for campaign_name in treatment_file["Kampagnenname"].unique().tolist(): #["BRAND"]: #
    temp = treatments[treatments["relates_to.campaign.name"].str.contains(campaign_name, case=False, regex=False)]
    if len(temp) == 0:
        print(f"No treatment found for campaign_name = {campaign_name}")
        continue
    used_treatments = pd.concat([used_treatments, temp])
    print(f"Added treatments for campaign_name = {campaign_name}, used_treatments length = {len(used_treatments)}")

In [ ]:
used_treatments[["id","relates_to.campaign.name"]].to_csv(f"/Users/karolinegriesbach/Downloads/used_treatments_brand_sea_{customer}.csv", index=False)

In [ ]:
temp = treatments[(treatments["relates_to.campaign.name"].str.contains("[P]_SEARCH_BRAND_", regex=False))&(treatments["relates_to.campaign.name"].str.contains(":DE"))].drop_duplicates(subset=["relates_to.campaign.name"]) 
temp["relates_to.campaign.name"].to_csv("treatments_search_brand_de.csv", index=False)
temp